FROM python:3.11-slim

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy project specification and code
COPY pyproject.toml ./
COPY src/ /app/src/

# Install dependencies and the packvote package
RUN pip install --default-timeout=1000 --no-cache-dir .

# Expose Streamlit port
EXPOSE 8501

# Command to run Streamlit app
CMD ["streamlit", "run", "src/packvote/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
